openapi: 3.0.0
info:
  title: China Member Service APIs
  version: v1
  contact:
    name: Mulan Inventory Service
    url: rock.yu@wework.com
  x-log:
    url: https://weconnect.github.io/china-mx-openapi/images/wework_logo.jpg
servers:
  - url: https://api-staging.wework.cn/chinaos/mulanInventoryService
    description: Staging Server
  - url: http://localhost:8080/mulanInventoryService
    description: Local Development Server
tags:
  - name: mulan
  - name: rpc
x-tagGroups:
  - name: API - v1
    tags:
      - mulan
      - rpc
components:
  schemas:
    CommonEnumVo:
      type: object
      properties:
        actionType:
          type: string
          description: 操作类型枚举
          enum:
            - CANCEL-取消订单
            - FINISH-终止订单
paths:
  /api/v1/rpc/products:
    get:
      tags:
        - rpc
      description: |
        List product, filter by building uuids, product types, product status
      operationId: products list
      parameters:
        - name: buildingUuid
          in: query
          description: filter by building's uuid
          schema:
            type: string
            format: uuid
        - name: productTypes
          in: query
          description: filter by product types
          schema:
            type: array
            items:
              type: string
              description: product type
              enum:
                - PRIVATE_OFFICE
                - HD
        - name: productStatuses
          in: query
          description: filter by product statuses
          schema:
            type: array
            items:
              type: string
              description: product status
              enum:
                - PENDING
                - ON_SALE
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    description: code
                    example: 0
                    type: integer
                  data:
                    items:
                      properties:
                        buildingName:
                          description: buildingName
                          example: 中海国际
                          type: string
                        buildingUuid:
                          description: buildingUuid
                          example: c1461271-3de7-4334-86f8-33352a4c4766
                          type: string
                        hasWindow:
                          description: hasWindow
                          type: boolean
                        hasInternalRoom:
                          description: hasInternalRoom
                          type: object
                          properties:
                            code:
                              description: code
                              example: 0
                              type: integer
                      type: object
                    type: array
                  msg:
                    description: msg
                    example: ""
                    type: string
