openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://127.0.0.1:8080
    description: mulan order
paths:
  /api/v1/mulan/orderItems/clear:
    put:
      tags:
        - move-in-out-controller
      operationId: clear
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/mulan/orderItems/moveIn:
    put:
      tags:
        - move-in-out-controller
      operationId: moveIn
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/mulan/orderItems/moveOut:
    put:
      tags:
        - move-in-out-controller
      operationId: moveOut
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/mulan/order:
    post:
      tags:
        - order-admin-controller
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceOrderDTO"
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/OrderCreatedVO"
  /api/v1/mulan/orderItem/{orderItemUuid}/confirm:
    put:
      tags:
        - order-admin-controller
      operationId: confirmOrder
      parameters:
        - name: orderItemUuid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/mulan/orderItems/cancel:
    put:
      tags:
        - order-admin-controller
      operationId: cancelOrder
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/mulan/orderItems/finish:
    put:
      tags:
        - order-admin-controller
      operationId: finishOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderFinishDTO"
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/mulan/orderItems:
    get:
      tags:
        - order-admin-controller
      operationId: listOrders
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderListVO"
  /api/v1/mulan/orderItem/{orderItemUuid}:
    get:
      tags:
        - order-admin-controller
      operationId: getOrderDetail
      parameters:
        - name: orderItemUuid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/OrderVO"
  /api/v1/crm/contract/{contractNo}:
    get:
      tags:
        - order-crm-controller
      operationId: getOrder
      parameters:
        - name: contractNo
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/OrderVO"
  /api/v1/crm/order:
    post:
      tags:
        - order-crm-controller
      operationId: createOrder_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpaceOrderDTO"
        required: true
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/OrderNoVO"
  /api/v1/crm/contract/{contractNo}/confirm:
    put:
      tags:
        - order-crm-controller
      operationId: confirmOrder_1
      parameters:
        - name: contractNo
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/crm/contract/{contractNo}/cancel:
    put:
      tags:
        - order-crm-controller
      operationId: cancelOrder_1
      parameters:
        - name: contractNo
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /api/v1/crm/contract/{contractNo}/releaseFutureReserve:
    put:
      tags:
        - order-crm-controller
      operationId: releaseFutureReserve
      parameters:
        - name: contractNo
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /rpc/v1/contract/{contractNo}:
    get:
      tags:
        - order-rpc-controller
      operationId: getOrder_1
      parameters:
        - name: contractNo
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/OrderVO"
  /rpc/v1/orders:
    get:
      tags:
        - order-rpc-controller
      operationId: getOrders
      parameters:
        - name: customerUuids
          in: query
          required: true
          schema:
            type: string
        - name: orderStatus
          in: query
          required: true
          schema:
            type: string
        - name: orderType
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderVO"
  /api/v1/fe/morningRun:
    post:
      tags:
        - schedule-controller
      operationId: morningRun
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: boolean
  /ping:
    get:
      tags:
        - ping-controller
      operationId: ping
      responses:
        200:
          description: OK
          content:
            "*/*":
              schema:
                type: object
                additionalProperties:
                  type: string
components:
  schemas:
    DiscountItemDTO:
      type: object
      properties:
        discountCategoryId:
          type: integer
          format: int64
        discount:
          type: number
        recursive:
          type: boolean
    OrderItemDTO:
      type: object
      properties:
        amount:
          type: number
        grossPrice:
          type: number
        cbp:
          type: number
        suggestedCbp:
          type: number
        currency:
          type: string
        quantity:
          type: integer
          format: int32
        skuUuid:
          type: string
        startTime:
          type: integer
          format: int64
        endTime:
          type: integer
          format: int64
        disbursement:
          type: boolean
        recursive:
          type: boolean
        type:
          type: string
        srRate:
          type: number
        remark:
          type: string
    ServiceOrderDTO:
      type: object
      properties:
        customerUuid:
          type: string
        startTime:
          type: integer
          format: int64
        endTime:
          type: integer
          format: int64
        amount:
          type: number
        grossPrice:
          type: number
        cbp:
          type: number
        suggestedCbp:
          type: number
        currency:
          type: string
        locationUuid:
          type: string
        remark:
          type: string
        orderItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemDTO"
        contractNo:
          type: string
        discountItems:
          type: array
          items:
            $ref: "#/components/schemas/DiscountItemDTO"
    OrderCreatedVO:
      type: object
      properties:
        orderNo:
          type: string
        creator:
          type: string
        createdDate:
          type: integer
          format: int64
    OrderFinishDTO:
      type: object
      properties:
        orderItemUuids:
          type: array
          items:
            type: string
        finishType:
          type: string
        finishTime:
          type: integer
          format: int64
    ActionVO:
      type: object
      properties:
        type:
          type: string
        enable:
          type: boolean
    OrderListVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        createdDate:
          type: integer
          format: int64
        createdBy:
          type: string
        lastModifiedDate:
          type: integer
          format: int64
        lastModifiedBy:
          type: string
        isDeleted:
          type: boolean
        version:
          type: integer
          format: int64
        orderItemNo:
          type: string
          description: 订单号
        amount:
          type: number
          description: 订单总额
        companyName:
          type: string
          description: 公司名称
        mainMember:
          type: string
          description: 主会员号
        orderType:
          type: string
          description: 订单状态
          enum:
            - SPACE
            - SERVICE
            - MIX
        startTime:
          type: integer
          format: int64
          description: 订单开始时间
        endTime:
          type: integer
          format: int64
          description: 订单结束时间
        action:
          type: array
          items:
            $ref: "#/components/schemas/ActionVO"
    DiscountItemVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        createdDate:
          type: integer
          format: int64
        createdBy:
          type: string
        lastModifiedDate:
          type: integer
          format: int64
        lastModifiedBy:
          type: string
        isDeleted:
          type: boolean
        version:
          type: integer
          format: int64
        discountCategoryId:
          type: integer
          format: int64
        discount:
          type: number
        recursive:
          type: boolean
    OrderItemVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        createdDate:
          type: integer
          format: int64
        createdBy:
          type: string
        lastModifiedDate:
          type: integer
          format: int64
        lastModifiedBy:
          type: string
        isDeleted:
          type: boolean
        version:
          type: integer
          format: int64
        amount:
          type: number
        grossPrice:
          type: number
        cbp:
          type: number
        suggestedCbp:
          type: number
        currency:
          type: string
        quantity:
          type: integer
          format: int32
        skuUuid:
          type: string
        startTime:
          type: integer
          format: int64
        endTime:
          type: integer
          format: int64
        disbursement:
          type: boolean
        orderStatus:
          type: string
        recursive:
          type: boolean
        type:
          type: string
        srRate:
          type: number
        remark:
          type: string
        skuType:
          type: string
        skuName:
          type: string
        skuSnapshot:
          type: string
        orderItemNo:
          type: string
        action:
          type: array
          items:
            $ref: "#/components/schemas/ActionVO"
    OrderVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        createdDate:
          type: integer
          format: int64
        createdBy:
          type: string
        lastModifiedDate:
          type: integer
          format: int64
        lastModifiedBy:
          type: string
        isDeleted:
          type: boolean
        version:
          type: integer
          format: int64
        customerUuid:
          type: string
        startTime:
          type: integer
          format: int64
        endTime:
          type: integer
          format: int64
        amount:
          type: number
        grossPrice:
          type: number
        cbp:
          type: number
        suggestedCbp:
          type: number
        currency:
          type: string
        locationUuid:
          type: string
        locationName:
          type: string
        remark:
          type: string
        contractNo:
          type: string
        relatedContractNo:
          type: string
        contractUrl:
          type: string
        contractType:
          type: string
        salesPolicy:
          $ref: "#/components/schemas/SalesPolicyVO"
        orderItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemVO"
        discountItems:
          type: array
          items:
            $ref: "#/components/schemas/DiscountItemVO"
    SalesPolicyVO:
      type: object
    CompanyDTO:
      type: object
      properties:
        crmCompanyId:
          type: string
    SpaceOrderDTO:
      type: object
      properties:
        customerUuid:
          type: string
        startTime:
          type: integer
          format: int64
        endTime:
          type: integer
          format: int64
        amount:
          type: number
        grossPrice:
          type: number
        cbp:
          type: number
        suggestedCbp:
          type: number
        currency:
          type: string
        locationUuid:
          type: string
        remark:
          type: string
        orderItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemDTO"
        companyDTO:
          $ref: "#/components/schemas/CompanyDTO"
        contractNo:
          type: string
        relatedContractNo:
          type: string
        contractUrl:
          type: string
        contractType:
          type: string
        salesPolicy:
          type: string
    OrderNoVO:
      type: object
      properties:
        orderNo:
          type: string
    PageInfoOrderListVO:
      type: object
      properties:
        page:
          type: integer
          format: int32
          description: 页码
          default: 0
        pageSize:
          type: integer
          format: int32
          description: 分页大小
          default: 50
        totalRows:
          type: integer
          format: int64
          description: 总条数
        totalPages:
          type: integer
          format: int32
          description: 总页数
        rows:
          type: array
          description: 订单信息
          items:
            $ref: "#/components/schemas/OrderListVO"
